spring:
  application:
    name: signature-app

  datasource:
    url: jdbc:mysql://localhost:3306/signature_app
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true